# .rubocop.yml

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1000

Metrics/BlockLength:
  Max: 25

Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'spec/**/*'
    - 'db/**/*'

